### ISSUE TITLE
RHEL 7.5 Beta has Rsync v3.1

### ISSUE THREAD

**Issue by temporaryaccount** [iuscommunity-pkg/rsync31u#1]
A little heads-up (just FYI), according to RHEL 7.5 Beta [Release Notes](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7-beta/html/7.5_release_notes/new_features_compiler_and_tools) the rsync package has been rebased to version 3.1.2. I just wonder whether there might be any conflicts with this package when 7.5 comes up.

**Comment by b-harper** [comment]
Hey @temporaryaccount,

I am glad to hear that we are not the only ones that have read the Release Notes for 7.5.   We already have [rsync31u-3.1.3-1][0] packages. They will me moved from the testing repository to the stable repository after tonight's automation run.  Our packages will work the same once RHEL 7.5 is released. 


[0]: https://github.com/iuscommunity-pkg/rsync31u/releases/tag/3.1.3-1
